### ISSUE TITLE
Bluetootheの安定性が悪い

### ISSUE THREAD

**Issue by TomohiroAoki** [UGOKU-Lab/FlexConsole_for_Bluetooth_Serial#1]
安定性が悪い
ラグがある
繋がらなくなる、
マイコン再接続ができない
送信できないことがある

**Comment by sanoshohei** [comment]
Bluetoothの接続性を改善した[v0.1.1-alpha](https://github.com/UGOKU-Lab/FlexConsole_for_Bluetooth_Serial/releases/tag/v0.1.1-alpha)をリリースしました。
アプリをバージョンアップし、動作の確認をお願いします。

なお、修正の内容は[601913db5fe31d5dc0240557cb461cf485da6704](https://github.com/UGOKU-Lab/FlexConsole_for_Bluetooth_Serial/commit/601913db5fe31d5dc0240557cb461cf485da6704)を参照してください。

**Comment by TomohiroAoki** [comment]
安定性、改善されたので閉じます。
